// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/4udiwe/avito-pr-service/internal/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPRRepo is a mock of PRRepo interface.
type MockPRRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPRRepoMockRecorder
	isgomock struct{}
}

// MockPRRepoMockRecorder is the mock recorder for MockPRRepo.
type MockPRRepoMockRecorder struct {
	mock *MockPRRepo
}

// NewMockPRRepo creates a new mock instance.
func NewMockPRRepo(ctrl *gomock.Controller) *MockPRRepo {
	mock := &MockPRRepo{ctrl: ctrl}
	mock.recorder = &MockPRRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPRRepo) EXPECT() *MockPRRepoMockRecorder {
	return m.recorder
}

// AssignReviewer mocks base method.
func (m *MockPRRepo) AssignReviewer(ctx context.Context, prID, reviewerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignReviewer", ctx, prID, reviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignReviewer indicates an expected call of AssignReviewer.
func (mr *MockPRRepoMockRecorder) AssignReviewer(ctx, prID, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignReviewer", reflect.TypeOf((*MockPRRepo)(nil).AssignReviewer), ctx, prID, reviewerID)
}

// AssignReviewers mocks base method.
func (m *MockPRRepo) AssignReviewers(ctx context.Context, prID string, reviewerIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignReviewers", ctx, prID, reviewerIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignReviewers indicates an expected call of AssignReviewers.
func (mr *MockPRRepoMockRecorder) AssignReviewers(ctx, prID, reviewerIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignReviewers", reflect.TypeOf((*MockPRRepo)(nil).AssignReviewers), ctx, prID, reviewerIDs)
}

// Create mocks base method.
func (m *MockPRRepo) Create(ctx context.Context, ID, title, authorID, statusName string, needMoreReviewers bool) (entity.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ID, title, authorID, statusName, needMoreReviewers)
	ret0, _ := ret[0].(entity.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPRRepoMockRecorder) Create(ctx, ID, title, authorID, statusName, needMoreReviewers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPRRepo)(nil).Create), ctx, ID, title, authorID, statusName, needMoreReviewers)
}

// GetAll mocks base method.
func (m *MockPRRepo) GetAll(ctx context.Context, limit, offset int) ([]entity.PullRequest, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, limit, offset)
	ret0, _ := ret[0].([]entity.PullRequest)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPRRepoMockRecorder) GetAll(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPRRepo)(nil).GetAll), ctx, limit, offset)
}

// GetByID mocks base method.
func (m *MockPRRepo) GetByID(ctx context.Context, ID string) (entity.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, ID)
	ret0, _ := ret[0].(entity.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPRRepoMockRecorder) GetByID(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPRRepo)(nil).GetByID), ctx, ID)
}

// GetPRStatuses mocks base method.
func (m *MockPRRepo) GetPRStatuses(ctx context.Context) ([]entity.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRStatuses", ctx)
	ret0, _ := ret[0].([]entity.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRStatuses indicates an expected call of GetPRStatuses.
func (mr *MockPRRepoMockRecorder) GetPRStatuses(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRStatuses", reflect.TypeOf((*MockPRRepo)(nil).GetPRStatuses), ctx)
}

// GetReviewersByPR mocks base method.
func (m *MockPRRepo) GetReviewersByPR(ctx context.Context, prID string) ([]entity.PRReviewer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewersByPR", ctx, prID)
	ret0, _ := ret[0].([]entity.PRReviewer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviewersByPR indicates an expected call of GetReviewersByPR.
func (mr *MockPRRepoMockRecorder) GetReviewersByPR(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewersByPR", reflect.TypeOf((*MockPRRepo)(nil).GetReviewersByPR), ctx, prID)
}

// GetStatusByStatusID mocks base method.
func (m *MockPRRepo) GetStatusByStatusID(ctx context.Context, statusID int) (entity.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatusByStatusID", ctx, statusID)
	ret0, _ := ret[0].(entity.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatusByStatusID indicates an expected call of GetStatusByStatusID.
func (mr *MockPRRepoMockRecorder) GetStatusByStatusID(ctx, statusID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatusByStatusID", reflect.TypeOf((*MockPRRepo)(nil).GetStatusByStatusID), ctx, statusID)
}

// ReassignReviewer mocks base method.
func (m *MockPRRepo) ReassignReviewer(ctx context.Context, prID, oldReviewerID, newReviewerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignReviewer", ctx, prID, oldReviewerID, newReviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReassignReviewer indicates an expected call of ReassignReviewer.
func (mr *MockPRRepoMockRecorder) ReassignReviewer(ctx, prID, oldReviewerID, newReviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignReviewer", reflect.TypeOf((*MockPRRepo)(nil).ReassignReviewer), ctx, prID, oldReviewerID, newReviewerID)
}

// UpdateNeedMoreReviewers mocks base method.
func (m *MockPRRepo) UpdateNeedMoreReviewers(ctx context.Context, ID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNeedMoreReviewers", ctx, ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNeedMoreReviewers indicates an expected call of UpdateNeedMoreReviewers.
func (mr *MockPRRepoMockRecorder) UpdateNeedMoreReviewers(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNeedMoreReviewers", reflect.TypeOf((*MockPRRepo)(nil).UpdateNeedMoreReviewers), ctx, ID)
}

// UpdateStatus mocks base method.
func (m *MockPRRepo) UpdateStatus(ctx context.Context, ID string, statusID int, mergedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, ID, statusID, mergedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockPRRepoMockRecorder) UpdateStatus(ctx, ID, statusID, mergedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockPRRepo)(nil).UpdateStatus), ctx, ID, statusID, mergedAt)
}

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUserRepo) GetByID(ctx context.Context, ID string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, ID)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepoMockRecorder) GetByID(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepo)(nil).GetByID), ctx, ID)
}

// GetRandomActiveTeammates mocks base method.
func (m *MockUserRepo) GetRandomActiveTeammates(ctx context.Context, teamID uuid.UUID, limit int, excludeIDs ...string) ([]entity.User, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, teamID, limit}
	for _, a := range excludeIDs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRandomActiveTeammates", varargs...)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandomActiveTeammates indicates an expected call of GetRandomActiveTeammates.
func (mr *MockUserRepoMockRecorder) GetRandomActiveTeammates(ctx, teamID, limit any, excludeIDs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, teamID, limit}, excludeIDs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomActiveTeammates", reflect.TypeOf((*MockUserRepo)(nil).GetRandomActiveTeammates), varargs...)
}
