// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/4udiwe/avito-pr-service/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUserRepo) GetByID(ctx context.Context, ID string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, ID)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepoMockRecorder) GetByID(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepo)(nil).GetByID), ctx, ID)
}

// SetActiveStatus mocks base method.
func (m *MockUserRepo) SetActiveStatus(ctx context.Context, userID string, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActiveStatus", ctx, userID, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActiveStatus indicates an expected call of SetActiveStatus.
func (mr *MockUserRepoMockRecorder) SetActiveStatus(ctx, userID, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActiveStatus", reflect.TypeOf((*MockUserRepo)(nil).SetActiveStatus), ctx, userID, isActive)
}

// MockPullReqeustRepo is a mock of PullReqeustRepo interface.
type MockPullReqeustRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPullReqeustRepoMockRecorder
	isgomock struct{}
}

// MockPullReqeustRepoMockRecorder is the mock recorder for MockPullReqeustRepo.
type MockPullReqeustRepoMockRecorder struct {
	mock *MockPullReqeustRepo
}

// NewMockPullReqeustRepo creates a new mock instance.
func NewMockPullReqeustRepo(ctrl *gomock.Controller) *MockPullReqeustRepo {
	mock := &MockPullReqeustRepo{ctrl: ctrl}
	mock.recorder = &MockPullReqeustRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullReqeustRepo) EXPECT() *MockPullReqeustRepoMockRecorder {
	return m.recorder
}

// ListByReviewer mocks base method.
func (m *MockPullReqeustRepo) ListByReviewer(ctx context.Context, reviewerID string) ([]entity.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByReviewer", ctx, reviewerID)
	ret0, _ := ret[0].([]entity.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByReviewer indicates an expected call of ListByReviewer.
func (mr *MockPullReqeustRepoMockRecorder) ListByReviewer(ctx, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByReviewer", reflect.TypeOf((*MockPullReqeustRepo)(nil).ListByReviewer), ctx, reviewerID)
}
