// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/4udiwe/avito-pr-service/internal/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepo) Create(ctx context.Context, ID, name string, teamID uuid.UUID, isActive bool) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ID, name, teamID, isActive)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepoMockRecorder) Create(ctx, ID, name, teamID, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepo)(nil).Create), ctx, ID, name, teamID, isActive)
}

// GetByTeamID mocks base method.
func (m *MockUserRepo) GetByTeamID(ctx context.Context, teamID uuid.UUID) ([]entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTeamID", ctx, teamID)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTeamID indicates an expected call of GetByTeamID.
func (mr *MockUserRepoMockRecorder) GetByTeamID(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTeamID", reflect.TypeOf((*MockUserRepo)(nil).GetByTeamID), ctx, teamID)
}

// GetRandomActiveUsers mocks base method.
func (m *MockUserRepo) GetRandomActiveUsers(ctx context.Context, limit int, excludeIDs ...string) ([]entity.User, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, limit}
	for _, a := range excludeIDs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRandomActiveUsers", varargs...)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandomActiveUsers indicates an expected call of GetRandomActiveUsers.
func (mr *MockUserRepoMockRecorder) GetRandomActiveUsers(ctx, limit any, excludeIDs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, limit}, excludeIDs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomActiveUsers", reflect.TypeOf((*MockUserRepo)(nil).GetRandomActiveUsers), varargs...)
}

// MockTeamRepo is a mock of TeamRepo interface.
type MockTeamRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepoMockRecorder
	isgomock struct{}
}

// MockTeamRepoMockRecorder is the mock recorder for MockTeamRepo.
type MockTeamRepoMockRecorder struct {
	mock *MockTeamRepo
}

// NewMockTeamRepo creates a new mock instance.
func NewMockTeamRepo(ctrl *gomock.Controller) *MockTeamRepo {
	mock := &MockTeamRepo{ctrl: ctrl}
	mock.recorder = &MockTeamRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepo) EXPECT() *MockTeamRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTeamRepo) Create(ctx context.Context, name string) (entity.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name)
	ret0, _ := ret[0].(entity.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTeamRepoMockRecorder) Create(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTeamRepo)(nil).Create), ctx, name)
}

// DeactivateTeamMembers mocks base method.
func (m *MockTeamRepo) DeactivateTeamMembers(ctx context.Context, teamName string) ([]entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateTeamMembers", ctx, teamName)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeactivateTeamMembers indicates an expected call of DeactivateTeamMembers.
func (mr *MockTeamRepoMockRecorder) DeactivateTeamMembers(ctx, teamName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateTeamMembers", reflect.TypeOf((*MockTeamRepo)(nil).DeactivateTeamMembers), ctx, teamName)
}

// GetAll mocks base method.
func (m *MockTeamRepo) GetAll(ctx context.Context, limit, offset int) ([]entity.Team, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, limit, offset)
	ret0, _ := ret[0].([]entity.Team)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockTeamRepoMockRecorder) GetAll(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockTeamRepo)(nil).GetAll), ctx, limit, offset)
}

// GetByName mocks base method.
func (m *MockTeamRepo) GetByName(ctx context.Context, name string) (entity.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(entity.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockTeamRepoMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockTeamRepo)(nil).GetByName), ctx, name)
}

// MockPRRepo is a mock of PRRepo interface.
type MockPRRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPRRepoMockRecorder
	isgomock struct{}
}

// MockPRRepoMockRecorder is the mock recorder for MockPRRepo.
type MockPRRepoMockRecorder struct {
	mock *MockPRRepo
}

// NewMockPRRepo creates a new mock instance.
func NewMockPRRepo(ctrl *gomock.Controller) *MockPRRepo {
	mock := &MockPRRepo{ctrl: ctrl}
	mock.recorder = &MockPRRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPRRepo) EXPECT() *MockPRRepoMockRecorder {
	return m.recorder
}

// ListByReviewer mocks base method.
func (m *MockPRRepo) ListByReviewer(ctx context.Context, reviewerID string) ([]entity.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByReviewer", ctx, reviewerID)
	ret0, _ := ret[0].([]entity.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByReviewer indicates an expected call of ListByReviewer.
func (mr *MockPRRepoMockRecorder) ListByReviewer(ctx, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByReviewer", reflect.TypeOf((*MockPRRepo)(nil).ListByReviewer), ctx, reviewerID)
}

// ReassignReviewer mocks base method.
func (m *MockPRRepo) ReassignReviewer(ctx context.Context, prID, oldReviewerID, newReviewerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignReviewer", ctx, prID, oldReviewerID, newReviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReassignReviewer indicates an expected call of ReassignReviewer.
func (mr *MockPRRepoMockRecorder) ReassignReviewer(ctx, prID, oldReviewerID, newReviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignReviewer", reflect.TypeOf((*MockPRRepo)(nil).ReassignReviewer), ctx, prID, oldReviewerID, newReviewerID)
}
